name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Tests
        run: go test ./... -tags ci -v -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash)